version: '3.4'

services:
  microblogging:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    working_dir: "/usr/src/app"
    environment:
      - LANG=C.UTF-8
      - FLASK_APP=run.py
      - SMTP_USER=postmaster@correo.io
      - SMTP_PASSWD=you-will-never-guess

  mongodb:
      image: aashreys/mongo-auth:latest
      volumes:
        - ./mongodb-data:/data/db
      environment:
        - AUTH=yes
        - MONGODB_ADMIN_USER=admin
        - MONGODB_ADMIN_PASS=admin
        - MONGODB_APPLICATION_DATABASE=microblogging
        - MONGODB_APPLICATION_USER=microblogging
        - MONGODB_APPLICATION_PASS=microblogging
      ports:
        - "27017:27017"
